### ISSUE TITLE
Spice doesn’t affect bottled heart

### ISSUE THREAD

**Issue by atlasmoon12** [kiooeht/Hubris#11]
When I picked up the first slice relic, it didn’t raise my bottled heart charges by 8

**Comment by kiooeht** [comment]
Seems to work fine for me.
![java_2018-10-13_23-51-00](https://user-images.githubusercontent.com/236842/46913507-14970480-cf43-11e8-97cc-cd4f3d7ca7b2.png)
![java_2018-10-13_23-51-11](https://user-images.githubusercontent.com/236842/46913508-19f44f00-cf43-11e8-907e-9c45d2dea36c.png)
Are you sure you didn't just miss it changing and misremember what you had before?

**Comment by atlasmoon12** [comment]
I was unable to replicate it, so maybe.

**Comment by kiooeht** [comment]
Alright, I'm going to close this issue. Feel free to reopen it if it happens again.
