### ISSUE TITLE
Crash with The Library event (1 of 20 cards from another character choice)

### ISSUE THREAD

**Issue by WolfHeroEX** [kiooeht/Hubris#15]
**Pastebin copy of error text:** https://pastebin.com/AbWLmn9W
**Run Screenshot (Relics, Seed, Character, the event itself):** https://i.imgur.com/6ATDGk6.png
**Mod List:** https://i.imgur.com/b45l2si.png

**Comment by kiooeht** [comment]
New release that fixes this
https://github.com/kiooeht/Hubris/releases/tag/v0.10.1
