### ISSUE TITLE
Necromantic Totem is completely unbalanced

### ISSUE THREAD

**Issue by Sincohalx** [kiooeht/Hubris#30]
Had an extremely aggressive deck fighting it that couldn't do anything--you can't kill the boss without getting a million curses, and killing the undeads interrupt them only for a turn, doesn't prevent the strength gain on the cultist, and fills my deck with acid.

Fought it with a defensive deck, the totem dealt 10 damage to itself every turn and I ended up with 4 curses in my deck. There is literally no counterplay to the boss--I either with and ruin my deck, or I die.

**Comment by kiooeht** [comment]
You realize you fought two completely different versions of the totem? Acid doesn't exist anymore. It was replaced by the self-damage.

Either way it doesn't matter, I removed it because I was tired of people complaining about it.

**Comment by AvangionQ** [comment]
I'm still playing with the totem version included ... so, how do you beat the totem without getting cursed?
