### ISSUE TITLE
Event named "The Experiment" contains unfinished text.

### ISSUE THREAD

**Issue by Huntokar04** [kiooeht/Hubris#35]
When navigating the event, all text in colors and brackets is replaced with Update Body Text.
![Screenshot](https://user-images.githubusercontent.com/45456538/50738834-3d403a80-11d0-11e9-863c-da0b964a26fa.jpg)

**Comment by kiooeht** [comment]
1. That's not the event "The Experiment". That's the event "UPDATE BODY TEXT".
2. The text isn't unfinished. That is the intended text of that event.
