### ISSUE TITLE
Asc 20 didn't have 2 bosses when the first boss was Grand Snecko

### ISSUE THREAD

**Issue by SilentJ28** [kiooeht/Hubris#9]
Was playing as Ironclad on Asc 20. After beating the Grand Snecko the game was over and I had won.
Expected a second boss.

**Comment by kiooeht** [comment]
Turns out this is an issue with BaseMod/Slay the Spire. Closing it here and opening an issue on BaseMod
https://github.com/daviscook477/BaseMod/issues/135
